import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import searchStyles from '@/styles/Search.module.css'
import Link from 'next/link';
import NavBar from './components/navBar';
import React from 'react'
import {useState, useEffect} from 'react'
import axios from 'axios'
import { GoogleMap, MarkerF, useJsApiLoader } from '@react-google-maps/api';
import RestaurantList from '../pages/components/RestaurantList'

export default function Home() {
  const [menu, setMenu] = useState([])

  useEffect(() => {
    async function getMenu(){
      const response = await axios.get(`/api/restaurant-menu?id=*`)
      setMenu(response.data)
      console.log(menu)
    }
    getMenu()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavBar/>

        <div className={styles.allDishes}>
            {menu.map((dish) => (
                        <div key={"menu"+dish.dish_id} className={styles.dish}>
                          <Link target="_blank" rel="noopener noreferrer" href={"/restaurant/" + dish.restaurant_id}>
                            <img src={`data:image/png;base64,${Buffer.from(dish.picture).toString('base64')}`} className={styles.picture} alt={dish.name}/>
                            <p className={styles.dishText}>${dish.price} - {dish.name}</p>
                          </Link>
                        </div>))}
        </div>
      </main>
    </>
  )
}

/*
const api_key = 'AIzaSyDXZy1wPNmoinJbzlCWnOBLqehpwXXGkPw';
const center = {lat:37.724286006635296,lng:-122.48000341090525};
const containerStyle = {width:'100%', height:'100%'};

function MyMap() {
  const {isLoaded} = useJsApiLoader({
    id: 'google-map-script',
    googleMapsApiKey: api_key
  })

  return isLoaded ? (
      <GoogleMap
        mapContainerStyle={containerStyle}
        center={center}
        zoom={15}
      >
      <MarkerF position={center}></MarkerF>
      </GoogleMap>
  ) : <></>
}
<div className={searchStyles.searchResult}>
          <h2 className={searchStyles.logo}>Logo</h2>
          <h1 className={searchStyles.name}>Restaraunt name</h1>
          <h2 className={searchStyles.rating}>Rating</h2>
          <h2 className={searchStyles.address}>Address</h2>
          <div className={searchStyles.map}>
            {MyMap()}
          </div>
        </div>
      <RestaurantList/>
*/